### ISSUE TITLE
There will be runs for which ALL SAMPLES RELEASED won't happen

### ISSUE THREAD

**Issue by Addy81** [eastgenomics/ansible-run-monitoring#18]
The Jira status workflow for sequencing runs won't always finish at ALL SAMPLES RELEASED.

If we don't get the data or if we decide not to process them.

For example:
<img width="419" alt="image" src="https://user-images.githubusercontent.com/33088252/216268394-e5045b6c-34b4-4443-bc65-40ec62ee6e9d.png">

**Comment by JasonLing95** [comment]
Is there any indication when we don't get the data or decide not to process it?

**Comment by Addy81** [comment]
There are 3 additional statuses which resolve tickets when no data is released:
![image](https://user-images.githubusercontent.com/33088252/223743690-5a6be1ff-7d3b-4089-9c51-25ebfb02205c.png)

Usually there's a notification from the lab or if something in QC making the whole run fail.

**Comment by JasonLing95** [comment]
So if a sample have 002 project created + a directory in staging52 + Jira ticket status of `DATA CANNOT BE PROCESSED` or `DATA CANNOT BE RELEASED`, is there any chance that the Jira ticket status will change?

**Comment by Addy81** [comment]
No I don't think so, we probably won't do anything with that data.

**Comment by JasonLing95** [comment]
so if the sample is old enough (more than 6 weeks since created) and have:
1. 002 project created
2. a directory in staging52
3. Jira ticket status of `DATA CANNOT BE PROCESSED` or `DATA CANNOT BE RELEASED` or `ALL SAMPLES RELEASED`

The sample can be flagged for auto deletion?

**Comment by JasonLing95** [comment]
- fix is to put in notification to Slack (for manual intervention) if there're runs older than 10 weeks which still fail criterias
